name: 'Docker Build'
description: 'build image, push image (optional)'

inputs:
  registry:
    description: 'docker registry'
    required: true
    default: $CONTAINERREGISTRY
  repository:
    description: 'repository'
    required: true  
    default: $REPOSITORY
  image-name:
    description: 'docker image name'
    required: true
    default: $IMAGENAME
  tag:
    description: 'docker image tag'
    required: true
    default: $TAG    
  build-args:
    description: 'docker build args'
    required: false
  dockerfile-path:
    description: 'dockerfile path'
    required: false
  push:
    description: 'also push image'
    required: true
    default: 'false'
  target:
    description: 'target'
    required: false


runs:
  using: "composite"
  steps: 
    - run: |
        export INPUT_REGISTRY=${{ inputs.registry }}
        export INPUT_BUILDARGS=${{ inputs.build-args }}
        export INPUT_IMAGENAME=${{ inputs.image-name }}
        echo "IMAGENAME=$INPUT_IMAGENAME" >> $GITHUB_ENV
        export INPUT_TAG=${{ inputs.tag }}
        export INPUT_DOCKERFILED_PATH=${{ inputs.dockerfile-path }} 
        export INPUT_FLAG_PUSH=${{ inputs.push }}
        export INPUT_REPOSITORY=${{ inputs.repository }}
        export INPUT_TARGET=${{ inputs.target }}
        $GITHUB_ACTION_PATH/build.sh
      shell: bash

