name: 'Docker Build'
description: 'build image, push image (optional)'

inputs:
  registry:
    description: 'docker registry'
    required: true
    default: $CONTAINERREGISTRY
  registry-subpath:
    description: 'registry subpath'
    required: true  
  image-name:
    description: 'docker image name'
    required: true
  build-args:
    description: 'docker build args'
    required: false
  dockerfile-path:
    description: 'dockerfile path'
    required: false
  push:
    description: 'also push image'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps: 
    - run: |
        GITHUBSHA=${{ github.sha }}
        TAG=$(echo $GITHUBSHA | cut -c1-6)
        echo "::set-env name=TAG::$TAG"
        export INPUT_REGISTRY=${{ inputs.registry }}
        export INPUT_BUILDARGS=${{ inputs.build-args }}
        export INPUT_IMAGENAME=${{ inputs.image-name }}
        export INPUT_TAG=$TAG
        export INPUT_DOCKERFILED_PATH=${{ inputs.dockerfile-path }} 
        export INPUT_FLAG_PUSH=${{ inputs.push }}
        $GITHUB_ACTION_PATH/build.sh
      shell: bash

